import { createWorkflow, createStep, StepResponse, WorkflowResponse } from "@medusajs/framework/workflows-sdk";
import { COMPANY_MODULE } from "../modules/company";
import { GOLDIE_MODULE } from "../modules/goldie";
import CompanyModuleService from "../modules/company/service";
import GoldieModuleService from "../modules/goldie/service";

type SpendGoldiesInput = {
  employee_id: string;
  company_id: string;
  amount: number;
  medusa_order_id: string;
  performed_by: string;
};

/**
 * RULES IMPLEMENTED:
 * 11. Atomic balance check: Fresh read of the employee's balance right before debit.
 * 12. Negative balance prevention: Explicitly ensure the balance never drops below zero.
 * 
 * This workflow handles the actual debit of Goldies and registers the transaction
 * and the link to the Medusa order.
 */

// 1. Validate and Lock Balance (Rules 11 & 12)
const validateAndLockBalanceStep = createStep(
  "validate-and-lock-balance",
  async (input: { employee_id: string; amount: number }, { container }) => {
    const companyService: CompanyModuleService = container.resolve(COMPANY_MODULE);
    
    // Rule 11: Fresh read for atomic-like guard
    const employee = await companyService.retrieveEmployee(input.employee_id);

    if (employee.goldie_balance < input.amount) {
      throw new Error(`Insufficient Goldie balance. Required: ${input.amount}, Available: ${employee.goldie_balance}`);
    }

    // Rule 12: Ensure no negative balance
    if (employee.goldie_balance - input.amount < 0) {
      throw new Error("Debit would result in a negative balance. Aborting.");
    }

    return new StepResponse({ ok: true }, { 
      employee_id: input.employee_id, 
      previousBalance: employee.goldie_balance 
    });
  }
);

// 2. Debit Employee Balance
const debitEmployeeGoldiesStep = createStep(
  "debit-employee-goldies",
  async (input: { employee_id: string; amount: number }, { container }) => {
    const companyService: CompanyModuleService = container.resolve(COMPANY_MODULE);
    
    const employee = await companyService.retrieveEmployee(input.employee_id);
    const previousBalance = employee.goldie_balance;
    const newBalance = previousBalance - input.amount;

    await companyService.updateEmployees({
      id: input.employee_id,
      goldie_balance: newBalance
    });

    return new StepResponse({ newBalance }, { 
      employee_id: input.employee_id, 
      previousBalance 
    });
  },
  async (compensationData, { container }) => {
    if (!compensationData) return;
    const companyService: CompanyModuleService = container.resolve(COMPANY_MODULE);
    await companyService.updateEmployees({
      id: compensationData.employee_id,
      goldie_balance: compensationData.previousBalance
    });
  }
);

// 3. Register Transaction and Link to Order
const registerSpendTransactionStep = createStep(
  "register-spend-transaction",
  async (input: SpendGoldiesInput, { container }) => {
    const goldieService: GoldieModuleService = container.resolve(GOLDIE_MODULE);

    const transaction = await goldieService.createGoldieTransactions({
      type: "spent",
      company_id: input.company_id,
      employee_id: input.employee_id,
      amount: input.amount,
      reference_type: "order",
      reference_id: input.medusa_order_id,
      performed_by: input.performed_by,
    });

    const goldieOrder = await goldieService.createGoldieOrders({
      medusa_order_id: input.medusa_order_id,
      employee_id: input.employee_id,
      transaction_id: transaction.id,
      total_goldies_cost: input.amount,
    });

    return new StepResponse({ transaction, goldieOrder }, { 
      transactionId: transaction.id, 
      goldieOrderId: goldieOrder.id 
    });
  },
  async (compensationData, { container }) => {
    if (!compensationData) return;
    const goldieService: GoldieModuleService = container.resolve(GOLDIE_MODULE);
    // Use the correct methods generated by MedusaService
    await goldieService.deleteGoldieOrders(compensationData.goldieOrderId);
    await goldieService.deleteGoldieTransactions(compensationData.transactionId);
  }
);

export const spendGoldiesWorkflow = createWorkflow(
  "spend-goldies",
  (input: SpendGoldiesInput) => {
    validateAndLockBalanceStep({ 
      employee_id: input.employee_id, 
      amount: input.amount 
    });
    
    debitEmployeeGoldiesStep({ 
      employee_id: input.employee_id, 
      amount: input.amount 
    });
    
    registerSpendTransactionStep(input);

    return new WorkflowResponse({ success: true });
  }
);
